### ISSUE TITLE
#10 - Not sending help notifications to the first user in the request

### ISSUE THREAD

**Issue by madewise** [CSC510-Team-Wise-Vilkomir-Sykes/Slackpoint#18]
It's expected to send the DMs to every user we request help from, but it doesn't send to the first user in the list

Related to #10

**Comment by ScenicJaguar101** [comment]
The issue was `command_parts` doesn't include the actual command "requesthelp" in the array, so the index of the task id should actually be 0 instead of 1

**Comment by ScenicJaguar101** [comment]
Completed in the recent commit. Closing
